name: 52pojie_sign
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  0 15 2 ? * * 
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 安装环境
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 签到       
      run: |
        python3 52pojie_sign.py 
      env:
        COOKIE: ${{ secrets.COOKIE }}
        QYWX_CORPID: ${{ secrets.QYWX_CORPID }}
        QYWX_CORPSECRET: ${{ secrets.QYWX_CORPSECRET }}
        QYWX_AGENTID: ${{ secrets.QYWX_AGENTID }}
        QYWX_MEDIA_ID: ${{ secrets.QYWX_MEDIA_ID }}
